name: M4
markdown: kramdown
highlighter: rouge
baseurl: /M4
permalink: none

title: Metals, Magnets, and Miscellaneous Materials
email: chrissie.c.l@gmail.com
description: Blog Introduction to Computational Condensed Matter Physics
