name: M4
markdown: redcarpet
pygments: true
baseurl: /M4

title: Metals, Magnets, and Miscelaneous Materials
email: chrissie.c.l@gmail.com
description: Blog Introduction to Computational Condensed Matter Physics
